AdvisorySG/ghost-advisory-theme

default.hbs, page-stories.hbs
=> Stories: Added basic filter function

.github/workflows/danger-js.yml, dangerfile.js, package.json, yarn.lock
Test PR for implementation of Danger JS.
=> Housekeeping: Implement Danger JS

assets/css/screen.css, default.hbs, post.hbs
Continuation from #31, resolves #23
=> Read progress bar

assets/css/screen.css, post.hbs
Post mockup
* Post metadata styling
* Responses section (commented out currently, since there's no implementation of responses feature yet)
=> Post mockup

home.hbs
This PR tracks all changes made to the Homepage and should be merged when the page is considered to be complete.
@BenitaWZX Please work with @unriellistic on the design of the Homepage and let us know if you have any issues with the theme! Feel free to upload screenshots here for ease of tracking.
=> Home: Implement full prototype

assets/css/screen.css, assets/css/toggledropdown.css, assets/js/toggledropdown.js, default.hbs, partials/icons/arrow-left.hbs, partials/icons/arrow-right.hbs, post.hbs
This PR tracks all changes made to Posts and should be merged when the pages are considered to be complete.
=> Post: Implement full prototype

page-impact.hbs
Base responsive skeletal structure of the impact page created based on prototype direction given.
Currently data and elements are statically placed. Will need to convert it if necessary.
=> Impact: Develop basic prototype #91

README.md
This PR adds the page `page-impact.hbs` to `README.md`.
=> Update README.md's list of custom page templates

assets/css/main.css, assets/css/screen.css, assets/css/tailwind.css, default.hbs, gulpfile.js, package.json, tailwind.config.js, yarn.lock
This PR serves as the initial setup of Tailwind (see https://github.com/AdvisorySG/ghost-advisory-theme/issues/135 for more details). The styling of the website should be mostly unaffected by this change, and after this PR is merged Tailwind utility classes can be used in the codebase.
=> Tailwind: Initial setup

home.hbs, partials/event-card.hbs
=> Implement sample event card

home.hbs
This PR removes the carousel from the Home page, since we no longer plan to have one.
=> Home: Remove carousel

assets/css/ghost/header.css
Added bg color to overlay to hide underlaying elements from being visible
=> Header: Fix for menu on Mobile #180

assets/js/eventCardFetcher.js
=> Made event cards responsive

default.hbs, error.hbs, home.hbs, package.json, page-impact.hbs, page-stories.hbs, page.hbs, post.hbs, tag.hbs, tailwind.config.js, yarn.lock
See commit messages. Should look at https://github.com/tailwindlabs/tailwindcss-typography#overriding-max-width and see if we can apply `prose` and `lg:prose-xl` to everything, then disable the `max-width` modifier.
=> Tailwind: Replace existing styling with Tailwind Typography

page-stories.hbs
=> page-stories.hbs: Use `{{asset}}` helper

assets/js/eventCardFetcher.js, default.hbs, package.json
=> Updated package.json for v4 API

tailwind.config.js
Fixed a bug in #236 where event card CSS on the homepage would not be loaded
=> Fixed config to load event card CSS on homepage

assets/js/eventCardFetcher.js
=> Added placeholder when no upcoming events

default.hbs, partials/footer.hbs
I have created the footer partial, without the Advisory logo at the bottom, and working links for all the anchor tags
=> [Issue #172]Added a footer partial

partials/story-postcard.hbs
Fixes an issue where the width of the image at the medium breakpoint can be smaller than expected.
=> Fix responsive width of story postcards

assets/js/eventCardFetcher.js, assets/js/partials/event-card-container.hbs, assets/js/partials/event-card.hbs, gulpfile.js, package.json, webpack.config.js
This PR replaces the current HTML generation code in `eventCardFetcher.js` with a Handlebars solution, which I believe would be a lot easier to maintain. This required the setup of Webpack and `handlebars-loader`.
Currently, I think the Gulp pipeline works fine, but let me know if you find any issues with this set up.
=> eventCardFetcher: Use Handlebars for HTML generation
